name: 'Build Test Deploy'
on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - develop
      - master
    types:
      - closed

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: git checkout
      uses: actions/checkout@v4

    - name: setup java
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        architecture: x64
        cache: maven

    - name: mvn deploy
      run: mvn --batch-mode --update-snapshots deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
